### PR TITLE
remove svgo-sync dependency

### PR DESCRIPTION
**Pull request by homerjam**
This lets us use the latest svgo, I've also updated the dependencies and changed formatting to prettier. Tests all passing.

### CODE REVIEW

**Comment by RobLoach** [comment]
This is great! Thank you so much :+1:

**Comment by ForbesLindesay** [comment]
This uses a native module that messes with the JavaScript event loop in pretty dangerous ways in order to achieve synchronous execution. It might be better to either not support synchronous usage of svgo, or spawn a separate process for it.

**Comment by homerjam** [comment]
This could be an alternative to `deasync` https://github.com/ybogdanov/node-sync

**Comment by ForbesLindesay** [comment]
That's the same problem. These native libraries completely mess with the JavaScript event loop and can be really fragile. I really don't think we should be putting them in jstransformers - if people want to install them, it should be a really conscious choice.

svgo-sync kept any potential issues really isolated to this library. If we must abandon svgo-sync, the only sensible option is to spawn a separate process for async work, but that could/should be done on jstransfomers as a whole. In the mean time, we should probably just update jstransfomer-svgo to only support async operation.

**Comment by homerjam** [comment]
Well `svgo-sync` is outdated, unmaintained and has issues so that's not really an option IMO.

I can use my fork for my purposes - which is simply to include svgs in pug templates.

I'm not really aware of the risks of messing with the event loop so I can't comment.

Perhaps a separate `jstransformer-svgo-sync` with a clear warning?

**Pull request merged**
